ToDoList/ToDoList/Controllers/ItemmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Data.Model;
using Data.ViewModel;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ToDoList.Controllers
{
    public class ItemmController : Controller
    {
        readonly HttpClient client = new HttpClient();
        public ItemmController()
        {
            client.BaseAddress = new Uri("https://localhost:44377/api/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        public IActionResult Index()
        {
            var Id = HttpContext.Session.GetString("id");
            if (Id != null)
            {
                return View(List());
            }
            return RedirectToAction("Login", "User");
        }

        public async Task<IActionResult> List()
        {
            IEnumerable<ItemmVM> itemm = null;
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var responseTask = await client.GetAsync("Itemms");
            if (responseTask.IsSuccessStatusCode)
            {
                var readTask = await responseTask.Content.ReadAsAsync<IList<ItemmVM>>();
                return Ok(new { data = readTask });
            }
            else
            {
                itemm = Enumerable.Empty<ItemmVM>();
                ModelState.AddModelError(string.Empty, "server error, try after some time");
            }
            return Json(itemm);
        }

        public async Task<ItemmVM> Paging(int pageSize, int pageNumber, string keyword)
        {
            try
            {
                client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
                var responseTask = await client.GetAsync("Itemms/PageSearch?" + "keyword=" + keyword + "&pageSize=" + pageSize + "&pageNumber=" + pageNumber);
                if (responseTask.IsSuccessStatusCode)
                {
                    var readTask = await responseTask.Content.ReadAsAsync<ItemmVM>();
                    return readTask;
                }

            }
            catch (Exception)
            {

            }
            return null;
        }

        [HttpGet("Itemm/PageData/")]
        public IActionResult PageData(IDataTablesRequest request)
        {
            var pageSize = request.Length;
            var pageNumber = request.Start / request.Length + 1;
            var keyword = request.Search.Value;
            //var data = Search(keyword, status).Result;
            //var filteredData = data;
            var dataPage = Paging(pageSize, pageNumber, keyword).Result;
            var response = DataTablesResponse.Create(request, dataPage.length, dataPage.filterlength, dataPage.data);
            return new DataTablesJsonResult(response, true);
        }

        public JsonResult InsertOrUpdate(ItemmVM itemmVM)
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var myContent = JsonConvert.SerializeObject(itemmVM);
            var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            if (itemmVM.Id == 0)
            {
                var result = client.PostAsync("itemms", byteContent).Result;
                return Json(result);
            }
            else
            {
                var result = client.PutAsync("itemms/" + itemmVM.Id, byteContent).Result;
                return Json(result);
            }
        }

        public async Task<JsonResult> GetById(int id)
        {
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            HttpResponseMessage response = await client.GetAsync("itemms");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsAsync<IList<ItemmVM>>();
                var itemm = data.FirstOrDefault(t => t.Id == id);
                var json = JsonConvert.SerializeObject(itemm, Formatting.None, new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                });
                return Json(json);
            }
            return Json("internal server error");
        }

        public JsonResult Delete(int id)
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var result = client.DeleteAsync("itemms/" + id).Result;
            return Json(result);
        }
    }
}

ToDoList/ToDoList/Controllers/SuppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Data.Model;
using Data.ViewModel;
using DataTables.AspNet.AspNetCore;
using DataTables.AspNet.Core;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using OfficeOpenXml;
using ToDoList.Report;

namespace ToDoList.Controllers
{
    public class SuppController : Controller
    {
        readonly HttpClient client = new HttpClient();
        public SuppController()
        {
            client.BaseAddress = new Uri("https://localhost:44377/api/");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        // GET: Supp
        public IActionResult Index()
        {
            var Id = HttpContext.Session.GetString("id");
            if (Id != null)
            {
                return View(List());
            }
            return RedirectToAction("Login", "User");
        }
        public async Task<IActionResult> List()
        {
            IEnumerable<Supp> supp = null;
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var responseTask = await client.GetAsync("Supps");
            if (responseTask.IsSuccessStatusCode)
            {
                var readTask = await responseTask.Content.ReadAsAsync<IList<Supp>>();
                return Ok(new { data = readTask });
            }
            else
            {
                supp = Enumerable.Empty<Supp>();
                ModelState.AddModelError(string.Empty, "server error, try after some time");
            }
            return Json(supp);
        }

        public JsonResult LoadSupplier()
        {
            IEnumerable<Supp> supp = null;

            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var responseTask = client.GetAsync("Supps");
            responseTask.Wait();
            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<IList<Supp>>();
                readTask.Wait();
                supp = readTask.Result;
            }
            else
            {
                supp = Enumerable.Empty<Supp>();
                ModelState.AddModelError(string.Empty, "Server Error");
            }
            return Json(supp);
        }

        public async Task<SuppVM> Paging(int pageSize, int pageNumber, string keyword)
        {
            try
            {
                client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
                var responseTask = await client.GetAsync("Supps/PageSearch?" + "keyword=" + keyword + "&pageSize=" + pageSize + "&pageNumber=" + pageNumber);
                if (responseTask.IsSuccessStatusCode)
                {
                    var readTask = await responseTask.Content.ReadAsAsync<SuppVM>();
                    return readTask;
                }

            }
            catch (Exception)
            {

            }
            return null;
        }

        [HttpGet("Supp/PageData/")]
        public IActionResult PageData(IDataTablesRequest request)
        {
            var pageSize = request.Length;
            var pageNumber = request.Start / request.Length + 1;
            var keyword = request.Search.Value;
            //var data = Search(keyword, status).Result;
            //var filteredData = data;
            var dataPage = Paging(pageSize, pageNumber, keyword).Result;
            var response = DataTablesResponse.Create(request, dataPage.length, dataPage.filterlength, dataPage.data);
            return new DataTablesJsonResult(response, true);
        }

        public JsonResult InsertOrUpdate(SuppVM suppVM)
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var myContent = JsonConvert.SerializeObject(suppVM);
            var buffer = System.Text.Encoding.UTF8.GetBytes(myContent);
            var byteContent = new ByteArrayContent(buffer);
            byteContent.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            if (suppVM.Id == 0)
            {
                var result = client.PostAsync("supps", byteContent).Result;
                return Json(result);
            }
            else
            {
                var result = client.PutAsync("supps/" + suppVM.Id, byteContent).Result;
                return Json(result);
            }
        }

        public async Task<JsonResult> GetById(int id)
        {
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            HttpResponseMessage response = await client.GetAsync("supps");
            if (response.IsSuccessStatusCode)
            {
                var data = await response.Content.ReadAsAsync<IList<SuppVM>>();
                var supp = data.FirstOrDefault(t => t.Id == id);
                var json = JsonConvert.SerializeObject(supp, Formatting.None, new JsonSerializerSettings()
                {
                    ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore
                });
                return Json(json);
            }
            return Json("internal server error");
        }

        public JsonResult Delete(int id)
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var result = client.DeleteAsync("supps/" + id).Result;
            return Json(result);
        }

        public async Task<IActionResult> exporttoExcel()
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var columnHeaders = new String[]
            {
                "ID",
                "Supplier Name"
            };

            byte[] result;

            using (var package = new ExcelPackage())
            {
                var worksheet = package.Workbook.Worksheets.Add("List Supplier");
                using (var cells = worksheet.Cells[1, 1, 1, 2])
                {
                    cells.Style.Font.Bold = true;
                }

                for (var i = 0; i < columnHeaders.Count(); i++)
                {
                    worksheet.Cells[1, i + 1].Value = columnHeaders[i];
                }

                var j = 2;
                HttpResponseMessage response = await client.GetAsync("supps");
                if (response.IsSuccessStatusCode)
                {
                    var readTask = await response.Content.ReadAsAsync<IList<Supp>>();
                    foreach (var supplier in readTask)
                    {
                        worksheet.Cells["A" + j].Value = supplier.Id;
                        worksheet.Cells["B" + j].Value = supplier.Name;
                        j++;
                    }
                }
                result = package.GetAsByteArray();
            }
            return File(result, "application/ms-excel", $"Supplier{DateTime.Now.ToString("hh:mm:ss MM/dd/yyyy")}.xlsx");
        }

        public async Task<IActionResult> exporttoCSV()
        {
            var client = new HttpClient
            {
                BaseAddress = new Uri("https://localhost:44377/api/")
            };
            client.DefaultRequestHeaders.Add("Authorization", HttpContext.Session.GetString("JWToken"));
            var columnHeaders = new String[]
            {
                "ID",
                "Supplier Name"
            };
            byte[] buffer;
            var suppcsv = new StringBuilder();
            HttpResponseMessage response = await client.GetAsync("supps");
            if (response.IsSuccessStatusCode)
            {
                var readTask = await response.Content.ReadAsAsync<IList<Supp>>();
                var supp = (from supplier in readTask
                            select new object[]
                            {
                                            supplier.Id,
                                            $"\"{supplier.Name}\""
                            }).ToList();
                supp.ForEach(line =>
                {
                    suppcsv.AppendLine(string.Join(",", line));
                });
            }
            buffer = Encoding.ASCII.GetBytes($"{string.Join(",", columnHeaders)}\r\n{suppcsv.ToString()}");
            return File(buffer, "text/csv", $"Supplier{DateTime.Now.ToString("hh:mm:ss MM/dd/yyyy")}.csv");
        }

        public async Task<IActionResult> Report(SuppVM suppVM)
        {
            SuppList supps = new SuppList();
            var readTask = await GetSupps();
            byte[] abytes = supps.PrepareReport(readTask);
            return File(abytes, "application/pdf", $"Supplier List{DateTime.Now.ToString("hh:mm:ss MM/dd/yyyy")}.pdf");
        }

        public async Task<List<SuppVM>> GetSupps()
        {
            List<SuppVM> supps = new List<SuppVM>();

ToDoList/ToDoList/Views/Layout/Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="~/monster-admin-lite-master/assets/images/favicon.png">
    <title>Monster Admin Template - The Most Complete & Trusted Bootstrap 4 Admin Template</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/monster-admin-lite-master/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/monster-admin-lite-master/monster-html/css/style.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="~/monster-admin-lite-master/monster-html/css/colors/blue.css" id="theme" rel="stylesheet">
    <script src="https://code.iconify.design/1/1.0.3/iconify.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body class="fix-header card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <svg class="circular" viewBox="25 25 50 50">
            <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="2" stroke-miterlimit="10" />
        </svg>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-toggleable-sm navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" asp-controller="User" asp-action="Home">
                        <!-- Logo icon -->
                        <b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="~/monster-admin-lite-master/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />

                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text -->
                        <span>
                            <!-- dark Logo text -->
                            <img src="~/monster-admin-lite-master/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                        </span>
                    </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto mt-md-0 ">
                        <!-- This is  -->
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up text-muted waves-effect waves-dark" href="javascript:void(0)"><i class="ti-menu"></i></a> </li>

                    </ul>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <li class="nav-item dropdown">
                            <a asp-controller="User" asp-action="Logout" class="btn btn-danger" role="button" data-toggle="tooltip" data-placement="bottom" title="Logout"><span class="iconify" data-icon="mdi-logout" data-inline="false"></span></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li>
                            <a asp-controller="User" asp-action="Index" class="waves-effect"><i class="fa fa-list m-r-10" aria-hidden="true"></i>To Do List</a>
                        </li>
                        <li>
                            <a asp-controller="Supp" asp-action="Index" class="waves-effect"><i class="fa fa-user m-r-10" aria-hidden="true"></i>Supplier</a>
                        </li>
                        <li>
                            <a asp-controller="Itemm" asp-action="Index" class="waves-effect"><i class="fa fa-bookmark  m-r-10" aria-hidden="true"></i>Item</a>
                        </li>
                    </ul>
                    <div class="text-center m-t-30">
                        <a href="https://wrappixel.com/templates/monsteradmin/" class="btn btn-danger"> Upgrade to Pro</a>
                    </div>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->

            @RenderBody();

            <!-- ============================================================== -->
            <!-- End Container fluid  -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- footer -->
            <!-- ============================================================== -->
            <footer class="footer text-center">
                © 2017 Monster Admin by wrappixel.com
            </footer>
            <!-- ============================================================== -->
            <!-- End footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    @RenderSection("scripts", required: false)
</body>

</html>